# Generated by Django 4.1.1 on 2022-10-13 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='updated_at',
            new_name='changed_at',
        ),
    ]
